name = "fortran-tokenizer"
version = "0.1.0"
license = "MIT"
author = "14NGiestas"
maintainer = "iangiestaspauli@gmail.com"
copyright = "Copyright 2022, 14NGiestas"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
[install]
library = false
